Futebol Americano/web_gerenciador/LiFFA/GerenciadorCampeonato/Areas/Admin/Controllers/GaleriaController.cs
using Campeonato.Aplicacao;
using Campeonato.Dominio;
using Campeonato.UI.WEB.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace Campeonato.UI.WEB.Areas.Admin
{
    public class GaleriaController : Controller
    {

        private readonly FotoVideoAplicacao appFotoVideo;
        private readonly TimeAplicacao appTime;

        //
        // GET: /Galeria/
        public GaleriaController()
        {
            appTime = TimeAplicacaoConstrutor.TimeAplicacaoADO();
            appFotoVideo = FotoVideoAplicacaoConstrutor.FotoVideoADO();
        }

        public ActionResult Index()
        {
            var listaFotosPorData = appFotoVideo.ListarDataFotoVideo();
            return View(listaFotosPorData);
        }

        public ActionResult PaginaInicial()
        {
            return View();
        }

        public ActionResult Galeria(string data)
        {
            var listaFotosPorData = appFotoVideo.ListarFotoVideoPorData(data);
            return View(listaFotosPorData);
        }

        public ActionResult GaleriaBase()
        {
            return View();
        }

        public ActionResult GaleriaVeteranos()
        {
            return View();
        }

        [PermissoesFiltro(Roles = "Admin")]
        public ActionResult FotosVideos(Partida partida)
        {
            //Trannsformo o objeto de partida em foto para salvar no banco de dados.
            FotosVideos fotosVideos = new FotosVideos();
            fotosVideos.IdCampeonato = partida.IdCampeonato;
            fotosVideos.IdPartida = partida.Id.ToString();
            fotosVideos.Rodada = partida.Rodada;
            fotosVideos.Caminho = partida.EscudoPequenoMandante;
            fotosVideos.Video = partida.GolMandante;
            fotosVideos.Descricao = partida.NomeCampeonato;
            if (partida.IdTimeMandante != null)
            {
                fotosVideos.IdTime = partida.IdTimeMandante;
            }
            else
            {
                fotosVideos.IdTime = partida.IdTimeVisitante;
            }

            if (appFotoVideo.Inserir(fotosVideos))
            {
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("FotosVideos", new RouteValueDictionary(
  new { controller = "Partida", action = "FotosVideos", id = partida.Id }));
            }
        }


        public ActionResult ListarFotosVideosParaEditar()
        {
            var listaFotosPorData = appFotoVideo.ListarFotosVideosParaEditar();
            return View(listaFotosPorData);
        }

        [PermissoesFiltro(Roles = "Admin")]
        public ActionResult Cadastrar()
        {
            var listaTimes = appTime.ListarTodos();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [PermissoesFiltro(Roles = "Admin")]
        public ActionResult Cadastrar(FotosVideos fotos)
        {
            return View();
        }

    }
}

Futebol Americano/web_gerenciador/LiFFA/GerenciadorCampeonato/Areas/Admin/Controllers/TimeController.cs
using Campeonato.Aplicacao;
using Campeonato.Dominio;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Campeonato.UI.WEB.Areas.Admin
{
    public class TimeController : Controller
    {
        private readonly TimeAplicacao appTime;
        private readonly FotoVideoAplicacao appFotosVideos;

        public TimeController()
        {
            appTime = TimeAplicacaoConstrutor.TimeAplicacaoADO();
            appFotosVideos = FotoVideoAplicacaoConstrutor.FotoVideoADO();
        }

        public ActionResult Index()
        {
            var listaDeTimes = appTime.ListarTodos();
            return View(listaDeTimes);
        }

        public ActionResult ListarTimesCampeonato(String idCampeonato)
        {
            var listaDeTimes = appTime.ListarTimesCampeonato(idCampeonato);
            return View(listaDeTimes);
        }

        public JsonResult ListarTimesCampeonatoJSON(String idCampeonato)
        {
            var listaDeTimes = appTime.ListarTimesCampeonato(idCampeonato);
            return Json(listaDeTimes, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Cadastrar(Time Time)
        {
            AtualizarImagem(Time);
            return RedirectToAction("Index");
        }

        private void AtualizarImagem(Time Time)
        {
            for (int i = 0; i < Request.Files.Count; i++)
            {
                HttpPostedFileBase arquivo = Request.Files[i];
                //Suas validações ...... //Salva o arquivo 
                if (arquivo.ContentLength > 0)
                {
                    var uploadPath = Server.MapPath("~/Content/images/escudo/");
                    string caminhoArquivo = Path.Combine(@uploadPath, Path.GetFileName(arquivo.FileName));
                    arquivo.SaveAs(caminhoArquivo);
                    Time.EscudoPequeno = arquivo.FileName;
                }
            }

            appTime.Salvar(Time);
        }

        public ActionResult Editar(string id)
        {
            var Time = appTime.ListarPorId(id);

            if (Time == null)
                return HttpNotFound();

            return View(Time);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(Time Time)
        {
            AtualizarImagem(Time);
            return RedirectToAction("Index");
        }

        public ActionResult Detalhes(string id)
        {
            var Time = appTime.ListarPorId(id);
            Time.ListaFotosVideos = appFotosVideos.ListarTime(id);
            if (Time == null)
                return HttpNotFound();

            return View(Time);
        }

        public ActionResult Excluir(string id)
        {
            var Time = appTime.ListarPorId(id);

            if (Time == null)
                return HttpNotFound();

            return View(Time);
        }

        [HttpPost, ActionName("Excluir")]
        [ValidateAntiForgeryToken]
        public ActionResult ExcluirConfirmado(string id)
        {
            var Time = appTime.ListarPorId(id);
            appTime.Excluir(Time);
            return RedirectToAction("Index");
        }

        //GETIMAGENS
        public ActionResult Image(string nomeImagem)
        {
            var dir = Server.MapPath("/Content/images/escudo");
            var path = Path.Combine(dir, nomeImagem);
            return base.File(path, "image/png");
        }
    }

}

Futebol Americano/web_gerenciador/LiFFA/GerenciadorCampeonato/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="~/Content/images/icons/Gol.png">
    <title>Futebol Lima Duarte</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    <script>
        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>

    <script>
        (function (d, s, id) {
            var ifr = document.getElementById('sm_frm1');

            if (ifr) {
                ifr.parentNode.removeChild(ifr);
            }
        });</script>


    <!-- GOOGLE ANALITCS-->
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
            m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-50618625-1', 'futebollimaduarte.com');
        ga('send', 'pageview');

    </script>


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-image: linear-gradient(green, green, #0B4917 60px)">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" style="color:white">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Futebol Lima Duarte", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse" style="color:white">
                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("Campeonato", "Index", "Campeonato", new { area = "Admin" }, htmlAttributes: new { id = "" })</li>
                    <li>@Html.ActionLink("Fotos", "Index", "Galeria", new { area = "Admin" }, htmlAttributes: new { id = "" })</li>
                    <li>@Html.ActionLink("Times", "Index", "Time", new { area = "Admin" }, htmlAttributes: new { id = "" })</li>
                    <li>@Html.ActionLink("Bolão", "Index", "Bolao", new { area = "Admin" }, htmlAttributes: new { id = "" })</li>
                    <li>@Html.ActionLink("Sobre", "About", "Home", new { area = "" },null)</li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <br />
    <div class="container body-content">
        @RenderBody()
        <hr />

        @*<footer>
            <p><a href="https://www.facebook.com/groups/602547396436819/#" target="_blank"><img src="~/Content/images/facebook.png" border="0" /></a>&nbsp;&nbsp; &copy; @DateTime.Now.Year - futebollimaduarte.com</p>

            <!--COMPARTILHAR FACEBOOK-->
            <div class="pull-left">
                <div class="fb-like " data-href="http://futebollimaduarte.com/" data-width="100%" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>
            </div>
            <!--COMENTARIO FACEBOOK-->
            <div class="pagination-centered">
                <div class="fb-comments" data-href="http://futebollimaduarte.com/" data-numposts="5" data-colorscheme="light"></div>
            </div>
            

        </footer>*@
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>